###
GET http://localhost:8080/companies
Content-Type: Application/Json

###
POST http://localhost:8080/companies
Content-Type: Application/Json

{
  "name": "my company"
}

###
GET http://localhost:8080/persons
Content-Type: Application/Json

###
GET http://localhost:8080/rides
Content-Type: Application/Json
